source "https://rubygems.org"

# Använd GitHub Pages gemmet för att säkerställa kompatibilitet
gem "github-pages", "~> 229", group: :jekyll_plugins

# Standardtema för nya Jekyll-webbplatser, du kan ändra detta till vad du vill
gem "minima", "~> 2.5"

# Om du använder GitHub Pages, behöver du inte inkludera jekyll gemmet separat.
# Du kan lägga till eventuella plugins här.
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows och JRuby inkluderar inte zoneinfo-filer, så inkludera tzinfo-data gemmet
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Kommentera bort eller ta bort wdm om du har problem med det
# gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lås `http_parser.rb`-gemmet till `v0.6.x` på JRuby-byggnader
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "webrick", "~> 1.7"